name: Deploy to WordPress.org
on:
  push:
    tags:
    - 'v*'
    - '!v*-alpha*'
    - '!v*-beta*'
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Use legacy Node
      uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: 8.16

    - name: Build
      run: | 
        npm install
        npm run build

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: popup-maker
